global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['localhost:9091']
    honor_labels: true

  - job_name: 'fuzzy_bn_service'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'